# battle: https://github.com/wsjeon/maddpg-rllib
group: "MPE"
name: "share/ddpg_simple_spread"

training:
  interface:
    type: "independent"
    population_size: -1
  config:
    # control the frequency of remote parameter update
    update_interval: 1
    saving_interval: 10
    batch_size: 1024
    optimizer: "Adam"
    actor_lr: 0.01
    critic_lr: 0.01
    lr: 0.01
    tau: 0.01  # soft update
    grad_norm_clipping: 0.5

rollout:
  type: "async"
  stopper: "simple_rollout"
  stopper_config:
    max_step: 1000
  metric_type: "simple"
  fragment_length: 500
  num_episodes: 320
  num_env_per_worker: 10
  terminate: "any"

evaluation:
  fragment_length: 25
  num_episodes: 100

env_description:
  #  scenario_name: "simple_spread"
  creator: "MPE"
  config:
    env_id: "simple_spread_v2"
    scenario_configs:
      max_cycles: 25

algorithms:
  DDPG:
    name: "DDPG"
    model_config:
      actor:
        network: mlp
        layers:
          - units: 64
            activation: ReLU
          - units: 64
            activation: ReLU
        output:
          activation: False
      critic:
        network: mlp
        layers:
          - units: 64
            activation: ReLU
          - units: 64
            activation: ReLU
        output:
          activation: False

    # set hyper parameter
    custom_config:
      gamma: 0.95
      use_cuda: False  # enable cuda or not

global_evaluator:
  name: "generic"

dataset_config:
  episode_capacity: 1000000
  learning_start: 2560
