# battle: https://github.com/wsjeon/maddpg-rllib
group: "Gym"
name: "share/dqn_lunar"

training:
  interface:
    type: "independent"
    population_size: -1
  config:
    # control the frequency of remote parameter update
    update_interval: 1
    saving_interval: 10
    batch_size: 1024
    optimizer: "Adam"
    lr: 0.001
    tau: 0.01  # soft update
    grad_norm_clipping: 2.0

rollout:
  type: "async"
  stopper: "simple_rollout"
  stopper_config:
    max_step: 1000
  metric_type: "simple"
  fragment_length: 1000
  num_episodes: 200
  episode_seg: 50
  terminate: "any"
  callback: "simultaneous"

env_description:
  creator: "Gym"
  config:
    env_id: "LunarLander-v2"

algorithms:
  DQN:
    name: "DQN"
    model_cofig:
      critic:
        network: mlp
        layers:
          - units: 64
            activation: ReLU
          - units: 64
            activation: ReLU
        output:
          activation: False
      custom_config:
        gamma: 0.95
        eps_max: 1.0
        eps_min: 0.1
        eps_anneal_time: 10000

global_evaluator:
  name: "generic"

dataset_config:
  episode_capacity: 1000000
  learning_start: 1000
