# battle: https://github.com/wsjeon/maddpg-rllib
group: "Gym"
name: "share/ppo_cartpole"

training:
  interface:
    type: "independent"
    population_size: -1
  config:
    # control the frequency of remote parameter update
    saving_interval: 10
    batch_size: 1024
    optimizer: "Adam"
    lr: 0.001
    ppo_epoch: 1
    entropy_coef: 0.02
    grad_norm_clipping: 0.5

rollout:
  type: "async"
  stopper: "simple_rollout"
  stopper_config:
    max_step: 1000
  metric_type: "simple"
  fragment_length: 200
  num_episodes: 100
  num_env_per_worker: 25
  terminate: "any"
  callback: "simultaneous"

env_description:
  creator: "Gym"
  config:
    env_id: "CartPole-v1"

algorithms:
  PPO:
    name: "PPO"
    model_cofig:
      actor:
        network: mlp
        layers:
          - units: 32
            activation: ReLU
          - units: 32
            activation: ReLU
        output:
          activation: False
      critic:
        network: mlp
        layers:
          - units: 32
            activation: ReLU
          - units: 32
            activation: ReLU
        output:
          activation: False

    custom_config:
      gamma: 0.95
      use_cuda: False  # enable cuda or not

global_evaluator:
  name: "generic"

dataset_config:
  episode_capacity: 100000
  learning_start: 2000
